# Generated by Django 5.0 on 2024-02-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_referral_code_customuser_referrer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_plan',
        ),
    ]
