# Generated by Django 5.0 on 2024-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_referral_code_redeemed',
        ),
    ]
