# Generated by Django 5.0 on 2024-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_payment_payment_url_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
