# Generated by Django 5.0 on 2024-02-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customuser_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.plan'),
        ),
    ]
