# Generated by Django 5.0 on 2024-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_referral_code_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
