# Generated by Django 5.0 on 2024-02-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
