# Generated by Django 5.0 on 2024-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_payment_status_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=str, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
