# Generated by Django 5.0 on 2024-02-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('active', 'Active'), ('over', 'Over')], default='inactive', max_length=10),
        ),
    ]
