# Generated by Django 5.0 on 2024-02-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_customuser_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_plan',
        ),
    ]
