# Generated by Django 5.0 on 2024-02-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_customuser_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
